name: Deploy Documentation

on:
  push:
    branches: [ main ]

# Allow GitHub Actions to write to repository and deploy to Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        pip install torch torchvision numpy scipy scikit-learn
        pip install -e .
    
    - name: Build documentation
      run: |
        cd torchium/docs
        sphinx-build -b html source build/html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./torchium/docs/build/html
        force_orphan: true
